server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/order/** 
        - id: Stock
          uri: http://localhost:8082
          predicates:
            - Path=/stock/** 
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/payment/** 
        - id: Dashboard
          uri: http://localhost:8084
          predicates:
            - Path= /dashboards/**
        - id: Rent
          uri: http://localhost:8085
          predicates:
            - Path=/rent/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://Order:8080
          predicates:
            - Path=/orderInfos/** 
        - id: Stock
          uri: http://Stock:8080
          predicates:
            - Path=/stockInfos/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/paymentInfos/** 
        - id: Dashboard
          uri: http://Dashboard:8080
          predicates:
            - Path= /dashboards/**
        - id: Rent
          uri: http://Rent:8080
          predicates:
            - Path=/rentInfos/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080